name: Web Automation Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Download repository
      - uses: actions/checkout@v4

      # Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Install Chrome and ChromeDriver
      - name: Setup Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1.7.3
        with:
          install-chromedriver: true

      # Setup gradlew
      - name: Setup gradlew
        run: chmod +x gradlew

      # Execute Gradle command for running Cucumber test
      - name: Execute Test
        run: ./gradlew test
